AWS_ACCESS_KEY_ID = "AKIA3BNTGPX65AXAVA6U"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-west-2"
AGENT_ID = "OBDOASWNGT"
AGENT_ALIAS_ID = "6RSQRHKCPT"
SEC_BUCKET_NAME = "secfedgar-source"
KB_ID = "FHFQEPJPA0"
DS_ID = "WOTXLIBMTP"

sync_finished = False
